resolver: lts-20.4
system-ghc: true
allow-newer: true

# NixOS support.
# Disabled by default; use as `stack run --nix` or `stack build --nix`.
nix:
  enable: false # Enable manually by passing --nix
  packages: [mysql57, openssl, zlib, postgresql]

packages:
- .

extra-deps:
  - beam-mysql-0.2.0.0@sha256:6c64358de5094463a70e8c71dbc99a38ae937d04a44cee9858e8a0779bb7b8dd,2282

extra-include-dirs:
  - /usr/local/opt/openssl/include
extra-lib-dirs:
  - /usr/local/opt/openssl/lib
